import type { Game } from './types';

const COLLECTION_GAME_NAMES = [
  'Skyrim Special Edition',
  'Fallout 4',
  'Skyrim',
  'Cyberpunk 2077',
  'Fallout New Vegas',
  'Stardew Valley',
  "Baldur's Gate 3",
  'Oblivion',
  'The Witcher 3',
  'Fallout 3',
  'Starfield',
  'Mount & Blade II: Bannerlord',
  'Morrowind',
  'Monster Hunter: World',
  'Blade & Sorcery',
  'Dragon Age: Origins',
  'Red Dead Redemption 2',
  'Elden Ring',
  'Stellar Blade',
  'Ready or Not',
  'Resident Evil 4 (2023)',
  'Subnautica',
  'Monster Hunter Wilds',
  'Dragon Age: Inquisition',
  '7 Days To Die',
  'Monster Hunter Rise',
  'My Summer Car',
  'Oblivion Remastered',
  'Palworld',
  'Dragon Age 2',
  'Marvel Rivals',
  'Helldivers 2',
  'The Sims 4',
  'Valheim',
  'Star Wars: Battlefront II (2017)',
  'Kingdom Come: Deliverance',
  'Resident Evil 2 (2019)',
  'Kingdom Come: Deliverance II',
  'Hogwarts Legacy',
  'Darkest Dungeon',
  'S.T.A.L.K.E.R. 2: Heart of Chornobyl',
  "Marvel's Spider-Man Remastered",
  "No Man's Sky",
  'Sekiro: Shadows Die Twice',
  'Resident Evil 3 (2020)',
  'TCG Card Shop Simulator',
  'Daggerfall Unity',
  'Dark Souls 3',
  "Dragon's Dogma 2",
  'Street Fighter 6',
  'Dark Souls',
  'Warhammer 40,000: Darktide',
  'Final Fantasy VII Remake',
  'Mass Effect Andromeda',
  'Fallout 76',
  'Schedule I',
  'Resident Evil Requiem',
  "Dragon's Dogma: Dark Arisen",
  'Enderal Special Edition',
  'MechWarrior 5: Mercenaries',
  'Kenshi',
  'Planet Zoo',
  'Knights of the Old Republic',
  'Supermarket Simulator',
  'Batman: Arkham Knight',
  'Crimson Desert',
  'State of Decay 2',
  'Final Fantasy VII Rebirth',
  'Jurassic World Evolution 2',
  'X4: Foundations',
  'The Witcher 2',
  'Slime Rancher',
  'Battle Brothers',
  'XCOM 2',
  'Days Gone',
  'Code Vein',
  'Divinity: Original Sin 2 - Definitive Edition',
  'Dying Light',
  'Star Wars Jedi: Fallen Order',
  'NieR: Automata',
  'Pathfinder: Kingmaker',
  'The Witcher',
  'Subnautica: Below Zero',
  'Clair Obscur: Expedition 33',
  'Pathfinder: Wrath of The Righteous',
  "Marvel's Spider-Man 2",
  'Resident Evil Village',
  'Hollow Knight: Silksong',
  'Black Myth: Wukong',
  'Dark Souls 2',
  'Dark Souls Remastered',
  'Dying Light 2',
  'Diablo II: Resurrected',
  'State of Decay',
  'Sifu',
  'The Killing Antidote',
  'Star Wars Jedi: Survivor',
  'Shadow of the Tomb Raider',
  'Kingdom Hearts III',
  'Ace Combat 7: Skies Unknown',
  'Dragon Ball: Sparking ZERO',
  'inZOI',
  'Slay The Spire II',
  'Knights of the Old Republic II',
  'Elden Ring Nightreign',
  'Nioh 2',
  'Horizon Zero Dawn',
  "Marvel's Spider-Man: Miles Morales",
  'Sun Haven',
  'My Winter Car',
  'BattleTech',
  'Grand Theft Auto V Legacy',
  'Dragon Ball Z: Kakarot',
  'Vampire: The Masquerade - Bloodlines',
  'Starbound',
  'Rimworld',
  'Dragon Age: The Veilguard',
  'Pillars of Eternity 2: Deadfire',
  'Warhammer 40,000: Rogue Trader',
  'Railroader',
  'Neverwinter Nights 2',
  "Ghost of Tsushima Director's Cut",
  "Marvel's Midnight Suns",
  'Cities: Skylines',
  "Assassin's Creed IV: Black Flag",
  'Far Cry 3',
  'Halo: The Master Chief Collection',
  'Graveyard Keeper',
  'Yakuza 0',
  'The Elder Scrolls Online',
  'Red Dead Redemption',
  'Dinkum',
  'Warhammer 40,000: Space Marine 2',
  'Fields of Mistria',
  'Dragon Quest XI S: Definitive Edition',
  'Avatar: Frontiers of Pandora',
  'Final Fantasy XII: The Zodiac Age',
  'Outward',
  'Dying Light: The Beast',
  'Car Mechanic Simulator 2021',
  "Assassin's Creed Unity",
  'Windrose',
  'Silent Hill 2 (2024)',
  'Gotham Knights',
  'GreedFall',
  'Lethal Company',
  "She Will Punish Them",
  "JoJo's Bizarre Adventure: All-Star Battle R",
  'Ground Branch',
  'Manor Lords',
  'Planet Crafter',
  'Balatro',
  'My Time at Sandrock',
  'Conan Exiles',
  'Borderlands 4',
  'God of War',
  'Coral Island',
  'Bellwright',
  'Horizon Forbidden West',
  'Door Kickers 2: Task Force North',
  'Subnautica 2',
  'Sons Of The Forest',
  'Gothic 1 Remake',
  'Avowed',
  'Into the Radius VR',
  'Yakuza Kiwami 2 Legacy',
  "Sid Meier's Civilization VI",
  'Batman: Arkham Asylum',
  'Abiotic Factor',
  'Dead as Disco',
  'Silent Hill f',
  'Control',
  'Tainted Grail: The Fall of Avalon',
  'The Outer Worlds 2',
  'Atomic Heart',
  'Tomb Raider I-III Remastered',
  'Dishonored',
  'Middle Earth: Shadow of War',
  'Prey (2017)',
  'Jagged Alliance 3',
  'R.E.P.O.',
  'One Piece Odyssey',
  'Star Wars Outlaws',
  'ICARUS',
  'Escape the Backrooms',
  'ELEX',
  'Spyro Reignited Trilogy',
  'Fable Anniversary',
  'BioShock',
  'Jurassic World Evolution 3',
  'Metal Gear Solid 3: Snake Eater - Master Collection',
  'Foxhole',
  'PEAK',
  'HumanitZ',
  'Astroneer',
  'Dragon Quest III HD-2D Remake',
  'Code Vein II',
  'Rune Factory: Guardians of Azuma',
  'Stray',
  'RuneScape: Dragonwilds',
  'Aska',
  'Cash Cleaner Simulator',
  'Metal Gear Solid 2: Sons of Liberty - Master Collection',
  'Dishonored 2',
  'Aliens: Dark Descent',
  'Wolcen: Lords of Mayhem',
  'Aliens: Fireteam Elite',
  'System Shock',
  'Dungeon Siege 1',
  'Travellers Rest',
  'Into The Radius 2',
  'Escape from Duckov',
  'Dead Rising Deluxe Remaster',
  'Bioshock Infinite',
  'Megastore Simulator',
  'Tomb Raider IV-VI Remastered',
  'LEGO Batman: Legacy of the Dark Knight',
  'World of Warcraft',
  'Bugsnax',
  'S.T.A.L.K.E.R. Anomaly',
  'Moonlighter',
  'RV There Yet',
  'Farming Simulator 25',
  "Nehrim: At Fate's Edge",
  'LOCKDOWN Protocol',
  "Burglin' Gnomes",
  'Road to Vostok',
  'Until Dawn',
  'Cobalt Core',
  'High on Life',
  'The Walking Trade',
  'Dishonored: Death of the Outsider',
  'Destroy All Humans 2 - Reprobed',
  'Wreckfest 2',
  'EmuVR',
  'Elegos'
];

const DOMAIN_ALIASES: Record<string, string> = {
  'Skyrim Special Edition': 'skyrimspecialedition',
  'Fallout 4': 'fallout4',
  Skyrim: 'skyrim',
  'Cyberpunk 2077': 'cyberpunk2077',
  'Fallout New Vegas': 'newvegas',
  'Stardew Valley': 'stardewvalley',
  "Baldur's Gate 3": 'baldursgate3',
  Oblivion: 'oblivion',
  'The Witcher 3': 'witcher3',
  'Fallout 3': 'fallout3',
  Starfield: 'starfield',
  Morrowind: 'morrowind',
  Subnautica: 'subnautica',
  Valheim: 'valheim',
  'The Sims 4': 'thesims4',
  Palworld: 'palworld',
  'No Man\'s Sky': 'nomanssky'
};

const GAME_IMAGES: Record<string, string> = {
  'Skyrim Special Edition': 'https://staticdelivery.nexusmods.com/Images/games/110/110-1571146700.jpg',
  Skyrim: 'https://staticdelivery.nexusmods.com/Images/games/110/110-1334346965.jpg',
  'Fallout 4': 'https://staticdelivery.nexusmods.com/Images/games/1151/1151-1432110129.jpg',
  'Cyberpunk 2077': 'https://staticdelivery.nexusmods.com/Images/games/3333/3333-1608036644.jpg',
  "Baldur's Gate 3": 'https://staticdelivery.nexusmods.com/Images/games/3474/3474-1599321511.jpg',
  'Stardew Valley': 'https://staticdelivery.nexusmods.com/Images/games/1303/1303-1455145338.jpg',
  'The Witcher 3': 'https://staticdelivery.nexusmods.com/Images/games/952/952-1431699500.jpg'
};

function domainFromName(name: string) {
  return DOMAIN_ALIASES[name] || name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '').trim();
}

export const GAMES: Game[] = COLLECTION_GAME_NAMES.map((name) => ({
  domainName: domainFromName(name),
  name,
  image: GAME_IMAGES[name] || '/mod-placeholder.svg'
}));
